version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-9
    steps:
      - checkout
      - restore_cache:
          key: stack-dependencies
      - run:
          name: Setup GHCJS and install Haskell dependencies
          command: stack --no-terminal --install-ghc test --only-dependencies
      - save_cache:
          key: stack-dependencies
          paths:
            - .stack-work/
            - "~/.stack"
            - "~/.ghcjs"
      - run:
          name: Build project and run tests
          command: stack --no-terminal test --haddock --no-haddock-deps
